### ISSUE TITLE
Does it support background service?

### ISSUE THREAD

**Issue by anggiedwarsa** [igrik12/battery_info#15]
I used this package using flutter_background_service. But got error:
W/FlutterJNI( 5246): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: com.igrik12.battery_info/stream. Response ID: 8

**Comment by anggiedwarsa** [comment]
And also how to cancel stream? canceling not working.

**Comment by anggiedwarsa** [comment]
I made PR for update. https://github.com/igrik12/battery_info/pull/16

**Comment by igrik12** [comment]
Merged the PR. Closing issue
