### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sjimy** [igrik12/battery_info#17]
Occurs when Flutter Activity is closed
Caught by the LeakCanary tool

![image](https://github.com/igrik12/battery_info/assets/16854281/15b97d31-ad88-4ffb-8e5e-e0094e9745a5)

**Comment by igrik12** [comment]
If you're subscribing to a stream, it is your responsibility to ensure it's properly disposed whenever you're not expecting any values to be pushed through
