### ISSUE TITLE
Support more platforms

### ISSUE THREAD

**Issue by bdlukaa** [igrik12/battery_info#2]
First of all, thank you for this awesome plugin :), the [official plugin](https://pub.dev/packages/battery) sucks

As flutter grows, we'd like this plugin to grow with it, so supporting more platforms is essential. 

- [ ] macOS support seems very reasonable, since It's not alpha anymore. The implementation may be similar to the iOS implementation. (see [this](https://developer.apple.com/documentation/uikit/uidevice/1620042-batterylevel))

❎ Web is likely out of reach (see [this](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API)), since the api is deprecated and I couldn't find another one :/

🚥 Windows and Linux are still in alpha stage, so it's is very unlikely that an implementation to these platforms would be good, since the api can change change anytime.

**Comment by igrik12** [comment]
Unable to confirm the MasOS implementation
