### ISSUE TITLE
Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle? error

### ISSUE THREAD

**Issue by sup3rx** [igrik12/battery_info#4]
when i tried to run example i'm getting below error

e: C:\Users\G\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\battery_info-1.0.7\android\src\main\kotlin\com\igrik12\battery_info\BatteryInfoPlugin.kt: (66, 36): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: C:\Users\G\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\battery_info-1.0.7\android\src\main\kotlin\com\igrik12\battery_info\BatteryInfoPlugin.kt: (69, 39): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Bundle?
e: C:\Users\G\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\battery_info-1.0.7\android\src\main\kotlin\com\igrik12\battery_info\BatteryInfoPlugin.kt: (83, 16): Type inference failed. Expected type mismatch: inferred type is Map<String, Any?> but Map<String, Any> was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':battery_info:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

**Comment by BrownieBits** [comment]
I am getting the same issue.

**Comment by savy-91** [comment]
Hi @sup3rx and @BrownieBits, I was having the same errors and I fixed them while migrating the plugin to null-safety. You can check this PR: https://github.com/igrik12/battery_info/pull/5

**Comment by BrownieBits** [comment]
i tried a few things and couldnt get it to pull... possibly doing it wrong...

battery_info:
    git:
      url: git@github.com:igrik12/battery_info.git
      path: pull/5
      
Please make sure you have the correct access rights
and the repository exists.

**Comment by savy-91** [comment]
n order to use that PR you can set the following in your pubspec:

`  battery_info:
    git:
      url: git@github.com:sungazer-io/battery_info.git
      ref: null-safety`


> @savy-91 i tried a few things and couldnt get it to pull... possibly doing it wrong...
> 
> battery_info:
> git:
> url: [git@github.com](mailto:git@github.com):igrik12/battery_info.git
> path: pull/5
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by igrik12** [comment]
@savy-91 
Thanks for the PR, merged and released with 1.0.8 version

**Comment by igrik12** [comment]
resolved
