### ISSUE TITLE
Future<AndroidBatteryInfo?>' can't be assigned to the parameter type 'Future<AndroidBatteryInfo>?'

### ISSUE THREAD

**Issue by lvlasuod** [igrik12/battery_info#8]
Hi

I installed the package and created an example same as the package, I got this error.

Running Gradle task 'assembleDebug'...
lib/main.dart:26:47: Error: The argument type 'Future<AndroidBatteryInfo?>' can't be assigned to the parameter type 'Future<AndroidBatteryInfo>?' because 'AndroidBatteryInfo?' is nullable and 'AndroidBatteryInfo' isn't.
 - 'Future' is from 'dart:async'.

pubsec.yaml

name: battery_health
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  battery_info:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

**Comment by thanhbinh84** [comment]
The example for StreamBuilder hasn't been updated yet 

![Screen Shot 2023-06-30 at 12 42 50](https://github.com/igrik12/battery_info/assets/366768/69cf5f71-c3fb-4e36-b572-ac469d0d9c6c)
