### ISSUE TITLE
Not receiving many battery updates when Android device is unplugged

### ISSUE THREAD

**Issue by BrnPer** [igrik12/battery_info#9]
Hello @igrik12 ! Before start, thank you for this package it's very useful. 

I'm facing an issue on Android when I disconnect my Android device from the wired to the computer. It receives a lot less battery updates that when is plugged in.

For example, while plugged in, the app receive updates every 200-300 ms, when unplugged it receives updates every 10 seconds...

Can you please help me fix this issue?

Thanks in advance.

**Comment by igrik12** [comment]
This is down to more frequent updates push by the native side which is the intended behaviour. You should be able to set the value to 200-300ms with the configuration.

**Comment by BrnPer** [comment]
Hi @igrik12 thank you for your reply.

From which configuration you're talking? In the Kotlin Platform Channel?
